[globals]
; 這些全大寫的變數名是保留字，有意義的
; app 這個目錄可以放在目前目錄的外頭，以相對路徑指定
; Controller : app/controllers/
; model : app/models/
AUTOLOAD=app/controllers/|app/models/|../fwcore/extend/
VANDER_PATH=../vander

; 設定時區
TZ=Asia/Taipei

; 設定語言
ENCODING=UTF-8

; UI 變數定義 view 放置的路徑
UI=app/views/

; 網站變數
ASSETS_PATH="assets"
SITE_TITLE="Tales of Phirmament"
ADMIN_EMAIL="talesworks@gmail.com"
CONTACT_EMAIL="talesworks@gmail.com"